# Generated by Django 6.0.6 on 2026-06-25 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('cidr', models.CharField(max_length=50, unique=True, verbose_name='بلوک IP/CIDR')),
                ('owner', models.CharField(blank=True, max_length=120, verbose_name='مالک/منبع')),
                ('total_addresses', models.PositiveIntegerField(default=0, verbose_name='تعداد آدرس')),
                ('is_available', models.BooleanField(default=True, verbose_name='قابل واگذاری')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
            ],
            options={
                'verbose_name': 'بلوک IP',
                'verbose_name_plural': 'بلوک\u200cهای IP',
                'ordering': ('cidr',),
            },
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان پلن')),
                ('service_type', models.CharField(choices=[('internet', 'اینترنت'), ('bandwidth', 'پهنای باند'), ('ip_lease', 'اجاره IP'), ('colocation', 'کولوکیشن')], max_length=20, verbose_name='نوع سرویس')),
                ('monthly_price_rial', models.BigIntegerField(default=0, verbose_name='قیمت ماهانه (ریال)')),
                ('bandwidth_mbps', models.PositiveIntegerField(default=0, verbose_name='پهنای باند (Mbps)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'پلن سرویس',
                'verbose_name_plural': 'پلن\u200cهای سرویس',
                'ordering': ('service_type', 'title'),
            },
        ),
        migrations.CreateModel(
            name='IPLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('assigned_cidr', models.CharField(max_length=50, verbose_name='محدوده واگذار شده')),
                ('start_date', models.DateField(verbose_name='شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='پایان')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('released', 'آزاد شده')], default='active', max_length=12, verbose_name='وضعیت')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='datacenter.ipblock', verbose_name='بلوک')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ip_leases', to='core.party', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'اجاره IP',
                'verbose_name_plural': 'اجاره\u200cهای IP',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('start_date', models.DateField(verbose_name='شروع')),
                ('end_date', models.DateField(verbose_name='پایان')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('suspended', 'تعلیق'), ('expired', 'منقضی')], default='active', max_length=12, verbose_name='وضعیت')),
                ('circuit_id', models.CharField(blank=True, max_length=80, verbose_name='شناسه سرویس/لینک')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.party', verbose_name='مشتری')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='datacenter.serviceplan', verbose_name='پلن')),
            ],
            options={
                'verbose_name': 'اشتراک دیتاسنتر',
                'verbose_name_plural': 'اشتراک\u200cهای دیتاسنتر',
                'ordering': ('-end_date',),
            },
        ),
    ]
