# Generated by Django 5.2.15 on 2026-06-25 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('name', models.CharField(max_length=140, verbose_name='نام سرویس')),
                ('host', models.CharField(max_length=255, unique=True, verbose_name='آدرس/IP')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('last_status', models.CharField(choices=[('up', 'آنلاین'), ('down', 'قطع'), ('unknown', 'نامشخص')], default='unknown', max_length=10, verbose_name='آخرین وضعیت')),
                ('last_latency_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='آخرین تاخیر (ms)')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین بررسی')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='تعداد خطای پیاپی')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
            ],
            options={
                'verbose_name': 'هدف مانیتورینگ',
                'verbose_name_plural': 'مانیتورینگ پینگ',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PingCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('status', models.CharField(choices=[('up', 'آنلاین'), ('down', 'قطع'), ('unknown', 'نامشخص')], max_length=10, verbose_name='وضعیت')),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='تاخیر (ms)')),
                ('output', models.TextField(blank=True, verbose_name='خروجی')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='datacenter.pingtarget', verbose_name='هدف')),
            ],
            options={
                'verbose_name': 'نتیجه پینگ',
                'verbose_name_plural': 'نتایج پینگ',
                'ordering': ('-created_at',),
            },
        ),
    ]
