# Generated by Django 5.2.15 on 2026-06-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_pingtarget_pingcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingtarget',
            name='environment',
            field=models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('internal', 'Internal')], default='production', max_length=20, verbose_name='محیط'),
        ),
        migrations.AddField(
            model_name='pingtarget',
            name='support_hint',
            field=models.CharField(blank=True, max_length=255, verbose_name='راهنمای اقدام هنگام قطعی'),
        ),
        migrations.AddField(
            model_name='pingtarget',
            name='support_owner',
            field=models.CharField(blank=True, max_length=120, verbose_name='مسئول/تیم پشتیبانی'),
        ),
        migrations.AddField(
            model_name='pingtarget',
            name='target_type',
            field=models.CharField(choices=[('website', 'سایت'), ('server', 'سرور'), ('mail', 'ایمیل'), ('network', 'شبکه'), ('other', 'سایر')], default='server', max_length=20, verbose_name='نوع'),
        ),
    ]
