# Generated by Django 5.2.15 on 2026-06-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0003_pingtarget_environment_pingtarget_support_hint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingcheck',
            name='alert_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال هشدار'),
        ),
        migrations.AddField(
            model_name='pingcheck',
            name='status_changed',
            field=models.BooleanField(default=False, verbose_name='تغییر وضعیت'),
        ),
        migrations.AddField(
            model_name='pingtarget',
            name='alert_emails',
            field=models.CharField(blank=True, help_text='چند ایمیل را با کاما جدا کنید.', max_length=500, verbose_name='ایمیل\u200cهای هشدار'),
        ),
        migrations.AddField(
            model_name='pingtarget',
            name='last_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین هشدار ایمیلی'),
        ),
    ]
