# Generated by Django 6.0.6 on 2026-06-25 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('personnel_code', models.CharField(max_length=30, unique=True, verbose_name='کد پرسنلی')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='عنوان شغلی')),
                ('department', models.CharField(blank=True, max_length=80, verbose_name='واحد')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع همکاری')),
                ('base_salary_rial', models.BigIntegerField(default=0, verbose_name='حقوق پایه (ریال)')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('suspended', 'تعلیق'), ('left', 'قطع همکاری')], default='active', max_length=12, verbose_name='وضعیت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرونده پرسنلی',
                'verbose_name_plural': 'پرونده\u200cهای پرسنلی',
                'ordering': ('personnel_code',),
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='ورود')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='خروج')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('remote', 'دورکاری'), ('leave', 'مرخصی'), ('absent', 'غیبت')], default='present', max_length=10, verbose_name='وضعیت')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hr.employeeprofile', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'حضور و غیاب',
                'verbose_name_plural': 'حضور و غیاب',
                'ordering': ('-date', 'employee'),
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('period', models.CharField(help_text='مثال: 1405-04', max_length=20, verbose_name='دوره حقوق')),
                ('base_rial', models.BigIntegerField(default=0, verbose_name='حقوق پایه (ریال)')),
                ('benefits_rial', models.BigIntegerField(default=0, verbose_name='مزایا (ریال)')),
                ('deductions_rial', models.BigIntegerField(default=0, verbose_name='کسورات (ریال)')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('approved', 'تأیید شده'), ('paid', 'پرداخت شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='hr.employeeprofile', verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'حقوق و دستمزد',
                'verbose_name_plural': 'حقوق و دستمزد',
                'ordering': ('-period', 'employee'),
                'unique_together': {('employee', 'period')},
            },
        ),
    ]
