# Generated by Django 5.2.15 on 2026-06-25 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='نام بانک'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='card_number',
            field=models.CharField(blank=True, max_length=19, verbose_name='شماره کارت'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='payroll_note',
            field=models.TextField(blank=True, verbose_name='توضیح پرداخت حقوق'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=34, verbose_name='شماره شبا'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='bank_tracking_code',
            field=models.CharField(blank=True, max_length=80, verbose_name='کد پیگیری بانکی'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_note',
            field=models.TextField(blank=True, verbose_name='توضیح پرداخت'),
        ),
        migrations.CreateModel(
            name='StaffRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='موبایل')),
                ('national_id', models.CharField(blank=True, max_length=10, verbose_name='کد ملی')),
                ('requested_department', models.CharField(blank=True, max_length=80, verbose_name='واحد درخواستی')),
                ('requested_job_title', models.CharField(blank=True, max_length=120, verbose_name='عنوان شغلی درخواستی')),
                ('requested_finance', models.BooleanField(default=False, verbose_name='دسترسی مالی')),
                ('requested_hr', models.BooleanField(default=False, verbose_name='دسترسی منابع انسانی')),
                ('requested_attendance', models.BooleanField(default=False, verbose_name='دسترسی حضور و غیاب')),
                ('requested_payroll', models.BooleanField(default=False, verbose_name='دسترسی حقوق و دستمزد')),
                ('requested_ticketing', models.BooleanField(default=True, verbose_name='دسترسی تیکتینگ')),
                ('requested_datacenter', models.BooleanField(default=False, verbose_name='دسترسی دیتاسنتر')),
                ('requested_user_manager', models.BooleanField(default=False, verbose_name='دسترسی مدیریت کاربران')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید ایمیل')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید مدیر')),
                ('status', models.CharField(choices=[('pending_email', 'در انتظار تایید ایمیل'), ('pending_approval', 'در انتظار تایید مدیر'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending_email', max_length=20, verbose_name='وضعیت')),
                ('manager_note', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_staff_requests', to=settings.AUTH_USER_MODEL, verbose_name='تاییدکننده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_registration', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست ثبت\u200cنام کارمند',
                'verbose_name_plural': 'درخواست\u200cهای ثبت\u200cنام کارمندان',
                'ordering': ('-created_at',),
            },
        ),
    ]
