# Generated by Django 5.2.15 on 2026-06-25 20:11

import django.db.models.deletion
from django.db import migrations, models
from datetime import time


def seed_default_shifts(apps, schema_editor):
    Shift = apps.get_model('hr', 'Shift')
    defaults = [
        ('اداری', time(8, 30), time(17, 0), 60, '#C39A4D'),
        ('پشتیبانی عصر', time(16, 0), time(23, 0), 30, '#2F6FED'),
        ('شیفت شب', time(23, 0), time(8, 0), 45, '#1E293B'),
    ]
    for name, start_time, end_time, break_minutes, color in defaults:
        Shift.objects.get_or_create(
            name=name,
            defaults={
                'start_time': start_time,
                'end_time': end_time,
                'break_minutes': break_minutes,
                'color': color,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employeeprofile_bank_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('name', models.CharField(max_length=80, verbose_name='نام شیفت')),
                ('start_time', models.TimeField(verbose_name='شروع')),
                ('end_time', models.TimeField(verbose_name='پایان')),
                ('break_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='استراحت (دقیقه)')),
                ('color', models.CharField(default='#C39A4D', max_length=7, verbose_name='رنگ نمایشی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
            ],
            options={
                'verbose_name': 'شیفت',
                'verbose_name_plural': 'شیفت\u200cها',
                'ordering': ('start_time', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('start_date', models.DateField(verbose_name='شروع برنامه')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='پایان برنامه')),
                ('weekdays', models.CharField(default='5,6,0,1,2', max_length=20, verbose_name='روزهای هفته')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='hr.employeeprofile', verbose_name='کارمند')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hr.shift', verbose_name='شیفت')),
            ],
            options={
                'verbose_name': 'برنامه شیفت',
                'verbose_name_plural': 'برنامه شیفت\u200cها',
                'ordering': ('-start_date', 'employee'),
                'indexes': [models.Index(fields=['start_date', 'end_date', 'is_active'], name='hr_shiftass_start_d_dbb4e5_idx')],
            },
        ),
        migrations.RunPython(seed_default_shifts, migrations.RunPython.noop),
    ]
