# Generated by Django 6.0.6 on 2026-06-25 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('is_closed', models.BooleanField(default=False, verbose_name='بسته\u200cشده')),
            ],
            options={
                'verbose_name': 'سال مالی',
                'verbose_name_plural': 'سال\u200cهای مالی',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد حساب')),
                ('name', models.CharField(max_length=120, verbose_name='نام حساب')),
                ('account_type', models.CharField(choices=[('asset', 'دارایی'), ('liability', 'بدهی'), ('equity', 'سرمایه'), ('income', 'درآمد'), ('expense', 'هزینه')], max_length=10, verbose_name='نوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account', verbose_name='حساب والد')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'حساب\u200cها (کدینگ)',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('number', models.PositiveIntegerField(verbose_name='شماره سند')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='شرح')),
                ('is_posted', models.BooleanField(default=False, verbose_name='ثبت قطعی')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='accounting.fiscalyear', verbose_name='سال مالی')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'اسناد',
                'ordering': ['-date', '-number'],
                'unique_together': {('fiscal_year', 'number')},
            },
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('debit_rial', models.BigIntegerField(default=0, verbose_name='بدهکار (ریال)')),
                ('credit_rial', models.BigIntegerField(default=0, verbose_name='بستانکار (ریال)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='شرح')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.account', verbose_name='حساب')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_lines', to='core.party', verbose_name='طرف\u200cحساب')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.voucher', verbose_name='سند')),
            ],
            options={
                'verbose_name': 'آرتیکل سند',
                'verbose_name_plural': 'آرتیکل\u200cهای سند',
            },
        ),
    ]
