# Generated by Django 5.2.15 on 2026-06-25 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان حساب')),
                ('bank_name', models.CharField(max_length=80, verbose_name='نام بانک')),
                ('account_number', models.CharField(blank=True, max_length=40, verbose_name='شماره حساب')),
                ('sheba_number', models.CharField(blank=True, max_length=34, verbose_name='شماره شبا')),
                ('card_number', models.CharField(blank=True, max_length=19, verbose_name='شماره کارت')),
                ('opening_balance_rial', models.BigIntegerField(default=0, verbose_name='مانده اولیه (ریال)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
                'ordering': ('bank_name', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان هزینه')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='دسته')),
                ('amount_rial', models.BigIntegerField(verbose_name='مبلغ (ریال)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('paid', 'پرداخت شده'), ('rejected', 'رد شده')], default='pending', max_length=12, verbose_name='وضعیت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('tracking_code', models.CharField(blank=True, max_length=80, verbose_name='کد پیگیری')),
                ('note', models.TextField(blank=True, verbose_name='توضیح')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.bankaccount', verbose_name='حساب پرداخت')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.party', verbose_name='طرف\u200cحساب')),
            ],
            options={
                'verbose_name': 'هزینه',
                'verbose_name_plural': 'هزینه\u200cها',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('number', models.CharField(max_length=40, unique=True, verbose_name='شماره فاکتور')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('issued', 'صادر شده'), ('paid', 'پرداخت شده'), ('overdue', 'سررسید گذشته'), ('canceled', 'لغو شده')], default='draft', max_length=12, verbose_name='وضعیت')),
                ('discount_rial', models.BigIntegerField(default=0, verbose_name='تخفیف (ریال)')),
                ('tax_rial', models.BigIntegerField(default=0, verbose_name='مالیات/ارزش افزوده (ریال)')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('tracking_code', models.CharField(blank=True, max_length=80, verbose_name='کد پیگیری')),
                ('note', models.TextField(blank=True, verbose_name='توضیح')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.party', verbose_name='مشتری/طرف\u200cحساب')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ('-issue_date', '-number'),
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('description', models.CharField(max_length=255, verbose_name='شرح')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price_rial', models.BigIntegerField(default=0, verbose_name='مبلغ واحد (ریال)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.invoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'ردیف فاکتور',
                'verbose_name_plural': 'ردیف\u200cهای فاکتور',
            },
        ),
    ]
